[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.10,<3.15"

[pypi-dependencies]

[feature.dev]
dependencies = { python = "3.14.*", black = "*", pandas-stubs = "*", pixi-pycharm = "*" }

[feature.coverage]
pypi-dependencies = { pytest = "*", slipcover = { git = "https://github.com/plasma-umass/slipcover", branch = "main" }}
tasks = { coverage = "slipcover --source src --json --pretty-print --out ./docs/pytest_coverage.json -m pytest" }

[feature.build]
dependencies = { hatchling = "*" }
tasks = { build = "hatchling build" }

[feature.docs]
# dependencies should match docs/requirements.txt
dependencies = { jupyter = "*", myst-parser = "*", nbsphinx = "*", notebook = "*", pydata-sphinx-theme = "*", sphinx = "*", sphinx-copybutton = "*" }
tasks = { docs = "./docs/make html" }
target = { win-64 = { tasks = { docs = ".\\docs\\make.bat html && .\\docs\\make.bat html && cmd /k start %cd%\\docs\\_build\\html\\index.html"} } }

[feature.lint]
dependencies = { black = "*", ruff = "*" }
tasks = { lint = "black --check ./src ./tests && ruff check ./src ./tests", lint-format = "black ./src ./tests && ruff format ./src ./tests"}

[feature.test]
dependencies = { pytest = "*", pytest-xdist = "*"}

[feature.conda-env]
dependencies = { gdal = "*", geojson = "*", geopandas = "*", matplotlib = "*", pyarrow = "*", xmltodict = "*" }
pypi-dependencies = { ouroboros-gis = { path = ".", editable = true } }

[feature.pypi-env]
dependencies = { python = "<3.14" }  # TODO pyogrio is not yet avaialable from PyPI for 3.14
pypi-dependencies = { ouroboros-gis = { path = ".", editable = true }, geojson = "*", geopandas = "*", matplotlib = "*", pyarrow = "*", xmltodict = "*" }

[feature.py310-conda]
dependencies = { python = "3.10.*" }
tasks = { test-py310-conda = "pytest -n auto" }

[feature.py310-pypi]
dependencies = { python = "3.10.*" }
tasks = { test-py310-pypi = "pytest -n auto" }

[feature.py311-conda]
dependencies = { python = "3.11.*" }
tasks = { test-py311-conda = "pytest -n auto" }

[feature.py311-pypi]
dependencies = { python = "3.11.*" }
tasks = { test-py311-pypi = "pytest -n auto" }

[feature.py312-conda]
dependencies = { python = "3.12.*" }
tasks = { test-py312-conda = "pytest -n auto" }

[feature.py312-pypi]
dependencies = { python = "3.12.*" }
tasks = { test-py312-pypi = "pytest -n auto" }

[feature.py313-conda]
dependencies = { python = "3.13.*" }
tasks = { test-py313-conda = "pytest -n auto" }

[feature.py313-pypi]
dependencies = { python = "3.13.*" }
tasks = { test-py313-pypi = "pytest -n auto" }

[feature.py314-conda]
dependencies = { python = "3.14.*" }
tasks = { test-py314-conda = "pytest -n auto", test = "pytest -vv" }

#[feature.py314-pypi]  # TODO pyogrio is not yet avaialable from PyPI for 3.14
#dependencies = { python = "3.14.*" }
#tasks = { test-py314-pypi = "pytest -n auto" }

[tasks.test-conda]
depends-on = [
	{ task = "test-py310-conda" },
	{ task = "test-py311-conda" },
	{ task = "test-py312-conda" },
	{ task = "test-py313-conda" },
	{ task = "test-py314-conda" },
]
	
[tasks.test-pypi]
depends-on = [
	{ task = "test-py310-pypi" },
	{ task = "test-py311-pypi" },
	{ task = "test-py312-pypi" },
	{ task = "test-py313-pypi" },
	#{ task = "test-py314-pypi" }  # TODO pyogrio is not yet avaialable from PyPI for 3.14
]

[tasks.test-all]
depends-on = [
	{ task = "test-conda" },
	{ task = "test-pypi" },
]

[tasks.release]
depends-on = [
	{ task = "lint-format" },
	{ task = "coverage" },
	{ task = "test-all" },
	{ task = "build", environment = "build" },
	{ task = "docs", environment = "docs" },
]

[environments]
default = ["default"]
dev = ["dev", "conda-env", "docs", "build", "test"]
coverage = ["coverage", "conda-env"]
docs = ["docs", "conda-env"]
build = ["build", "conda-env"]
lint = ["lint", "conda-env"]
test = ["test", "conda-env"]
conda-env = ["conda-env"]
pypi-env = ["pypi-env"]
py310-conda = ["py310-conda", "conda-env", "test"]
py311-conda = ["py311-conda", "conda-env", "test"]
py312-conda = ["py312-conda", "conda-env", "test"]
py313-conda = ["py313-conda", "conda-env", "test"]
py314-conda = ["py314-conda", "conda-env", "test"]
py310-pypi = ["py310-pypi", "pypi-env", "test"]
py311-pypi = ["py311-pypi", "pypi-env", "test"]
py312-pypi = ["py312-pypi", "pypi-env", "test"]
py313-pypi = ["py313-pypi", "pypi-env", "test"]
# py314-pypi = ["py314-pypi", "pypi-env", "test"]  # TODO pyogrio is not yet avaialable from PyPI for 3.14
