name: Test Python Prerelease
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]
jobs:
  test-on-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false
      - run: |
          docker run --name tester --rm -id --mount type=bind,source=./,target=/root/checkout ghcr.io/corbel-spatial/here-be-dragons:next
          docker exec -w /root/checkout tester uv pip install --system . pytest
          docker exec -w /root/checkout tester pytest
