# https://github.com/marketplace/actions/setup-pixi
name: Pytest - Linux
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ test-py310-pypi, test-py311-pypi, test-py312-pypi, test-py313-pypi,
                       test-py310-conda, test-py311-conda, test-py312-conda, test-py313-conda, test-py314-conda]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pixi.lock
            pixi.toml
            pyproject.toml
            README.md
            src
            tests
          sparse-checkout-cone-mode: false
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.56.0
          cache: true
          environments: default
      - run: pixi run ${{ matrix.environment }}
