# https://github.com/marketplace/actions/setup-pixi
name: Pytest - macOS
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**", ".github/workflows/pytest-macos.yml" ]
jobs:
  pytest:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ test-py310-pypi, test-py311-pypi, test-py312-pypi, test-py313-pypi,
                       test-py310-conda, test-py311-conda, test-py312-conda, test-py313-conda, ]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pixi.lock
            pyproject.toml
            README.md
            src/ouroboros
            tests
          sparse-checkout-cone-mode: false
      - run: brew install proj
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.55.0
          cache: true
          environments: default
      - run: pixi run ${{ matrix.environment }}
