# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Pytest - Windows - 3.14
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.14.0-rc.1"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .[raster]
    - name: Test with pytest
      run: |
        pytest ./tests/tests.py
