# https://github.com/marketplace/actions/setup-miniconda
name: Pytest - macOS
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**", ".github/workflows/pytest-macos.yml" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pyproject.toml
            src/ouroboros
            tests
          sparse-checkout-cone-mode: false
      - name: Check paths
        shell: bash -el {0}
        run: |
          pwd
          ls -la
          ls -la src/ouroboros
          ls -la tests
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
      - name: Install conda dependencies
        shell: bash -el {0}
        run: |
          conda activate test
          conda install "gdal>=3.8" "libsqlite>=3.37" "sqlite>=3.37" -c conda-forge
      - name: Install uv
        shell: bash -el {0}
        run: |
          conda activate test
          brew install uv
      - name: Install with uv pip
        shell: bash -el {0}
        run: |
          conda activate test
          uv pip install . --group test
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          conda activate test
          python -m pytest -n auto ./tests/tests.py