# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Pytest - Linux
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3-pip python3-pytest python3-rasterio -y
        python3 -m pip install build
        python3 -m build
        python3 -m pip install .
    - name: Test with pytest
      run: |
        python3 -m pytest ./tests/tests.py
