# https://github.com/marketplace/actions/setup-miniconda
name: Pytest - Linux
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**", ".github/workflows/pytest-linux.yml" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ test-py39, test-py310, test-py311, test-py312, test-py313 ]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pixi.lock
            pyproject.toml
            src/ouroboros
            tests
          sparse-checkout-cone-mode: false
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.55.0
          cache: true
          environments: ${{ matrix.environment }}
      - run: pixi run -e ${{ matrix.environment }} test
